dist: xenial
branches:
  only:
    - master
language: csharp
solution: ServiceOuterInnerResourcePlugin.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build ServiceOuterInnerResourcePlugin.sln
  - dotnet test -v n ServiceOuterInnerResourcePlugin.Integration.Test/ServiceOuterInnerResourcePlugin.Integration.Test.csproj
