dist: xenial
branches:
  only:
    - master
language: csharp
solution: ServiceMachineAreaPlugin.sln
mono: none
dotnet: 2.2
services:
- mysql
script:
  - dotnet restore
  - dotnet build ServiceMachineAreaPlugin.sln
  - dotnet test -v n ServiceMachineAreaPlugin.Integration.Test/ServiceMachineAreaPlugin.Integration.Test.csproj
